# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MiCustomers',
            fields=[
                ('newdata', models.IntegerField(null=True, blank=True)),
                ('facilityid', models.CharField(max_length=20, null=True, blank=True)),
                ('fcustcode', models.CharField(max_length=20, null=True, blank=True)),
                ('fcompany', models.CharField(max_length=50, null=True, blank=True)),
                ('fcfname', models.CharField(max_length=50, null=True, blank=True)),
                ('fclname', models.CharField(max_length=50, null=True, blank=True)),
                ('faddr1', models.CharField(max_length=50, null=True, blank=True)),
                ('faddr2', models.CharField(max_length=50, null=True, blank=True)),
                ('fcity', models.CharField(max_length=50, null=True, blank=True)),
                ('fstate', models.CharField(max_length=50, null=True, blank=True)),
                ('fzip', models.CharField(max_length=50, null=True, blank=True)),
                ('fphone', models.CharField(max_length=50, null=True, blank=True)),
                ('ffax', models.CharField(max_length=50, null=True, blank=True)),
                ('fcusttype', models.CharField(max_length=50, null=True, blank=True)),
                ('fcreditlim', models.CharField(max_length=50, null=True, blank=True)),
                ('fservrep', models.CharField(max_length=50, null=True, blank=True)),
                ('fbaddr1', models.CharField(max_length=50, null=True, blank=True)),
                ('fbaddr2', models.CharField(max_length=50, null=True, blank=True)),
                ('fbcity', models.CharField(max_length=50, null=True, blank=True)),
                ('fbstate', models.CharField(max_length=50, null=True, blank=True)),
                ('fbzip', models.CharField(max_length=50, null=True, blank=True)),
                ('fcomment', models.CharField(max_length=50, null=True, blank=True)),
                ('fhold', models.CharField(max_length=50, null=True, blank=True)),
                ('fbroker', models.CharField(max_length=50, null=True, blank=True)),
                ('funiqsale', models.CharField(max_length=50, null=True, blank=True)),
                ('funiqsalby', models.CharField(max_length=50, null=True, blank=True)),
                ('funiqpo', models.CharField(max_length=50, null=True, blank=True)),
                ('funiqpoby', models.CharField(max_length=50, null=True, blank=True)),
                ('fbillpal', models.CharField(max_length=50, null=True, blank=True)),
                ('fcommitby', models.CharField(max_length=50, null=True, blank=True)),
                ('funearnper', models.CharField(max_length=50, null=True, blank=True)),
                ('fisdist', models.CharField(max_length=50, null=True, blank=True)),
                ('fdistcarr', models.CharField(max_length=50, null=True, blank=True)),
                ('fdisttran', models.CharField(max_length=50, null=True, blank=True)),
                ('fdistcube', models.CharField(max_length=50, null=True, blank=True)),
                ('fdocinchrg', models.CharField(max_length=50, null=True, blank=True)),
                ('fgldocin', models.CharField(max_length=50, null=True, blank=True)),
                ('fdocoutchg', models.FloatField(null=True, blank=True)),
                ('fgldocout', models.FloatField(null=True, blank=True)),
                ('fdoclotchg', models.FloatField(null=True, blank=True)),
                ('fgldoclot', models.FloatField(null=True, blank=True)),
                ('fdelwgtbrk', models.FloatField(null=True, blank=True)),
                ('fmininvchg', models.FloatField(null=True, blank=True)),
                ('ffulpalchg', models.FloatField(null=True, blank=True)),
                ('fglfulpal', models.FloatField(null=True, blank=True)),
                ('fcsepckchg', models.FloatField(null=True, blank=True)),
                ('fglcsepick', models.FloatField(null=True, blank=True)),
                ('flinechrg', models.FloatField(null=True, blank=True)),
                ('fgllinechg', models.FloatField(null=True, blank=True)),
                ('fbolreport', models.CharField(max_length=100, null=True, blank=True)),
                ('fwrreport', models.CharField(max_length=100, null=True, blank=True)),
                ('finvreport', models.CharField(max_length=100, null=True, blank=True)),
                ('fpikreport', models.CharField(max_length=100, null=True, blank=True)),
                ('fbilreport', models.CharField(max_length=100, null=True, blank=True)),
                ('finvcrept', models.CharField(max_length=100, null=True, blank=True)),
                ('fincwrept', models.CharField(max_length=100, null=True, blank=True)),
                ('foutcwrept', models.CharField(max_length=100, null=True, blank=True)),
                ('fcredrept', models.CharField(max_length=100, null=True, blank=True)),
                ('fchckrept', models.CharField(max_length=100, null=True, blank=True)),
                ('fraternwl', models.CharField(max_length=100, null=True, blank=True)),
                ('favgbiling', models.CharField(max_length=100, null=True, blank=True)),
                ('fwho', models.CharField(max_length=100, null=True, blank=True)),
                ('fdatestamp', models.CharField(max_length=100, null=True, blank=True)),
                ('fmatprod', models.CharField(max_length=100, null=True, blank=True)),
                ('fmatchday', models.CharField(max_length=100, null=True, blank=True)),
                ('fusepick', models.CharField(max_length=100, null=True, blank=True)),
                ('fcube', models.CharField(max_length=100, null=True, blank=True)),
                ('fcubewgt', models.CharField(max_length=100, null=True, blank=True)),
                ('fcfullpart', models.CharField(max_length=100, null=True, blank=True)),
                ('fpaljack', models.CharField(max_length=100, null=True, blank=True)),
                ('fovercube', models.CharField(max_length=100, null=True, blank=True)),
                ('fmbolrept', models.CharField(max_length=100, null=True, blank=True)),
                ('fonlypar', models.CharField(max_length=100, null=True, blank=True)),
                ('fpalexch', models.CharField(max_length=100, null=True, blank=True)),
                ('fstatus', models.CharField(max_length=100, null=True, blank=True)),
                ('mailboxnme', models.CharField(max_length=100, null=True, blank=True)),
                ('schedintim', models.CharField(max_length=100, null=True, blank=True)),
                ('schedoutim', models.CharField(max_length=100, null=True, blank=True)),
                ('ediconfcom', models.CharField(max_length=100, null=True, blank=True)),
                ('confirmord', models.CharField(max_length=100, null=True, blank=True)),
                ('active', models.CharField(max_length=100, null=True, blank=True)),
                ('actdate', models.CharField(max_length=100, null=True, blank=True)),
                ('tunnelseq', models.CharField(max_length=100, null=True, blank=True)),
                ('fcomstatus', models.CharField(max_length=100, null=True, blank=True)),
                ('fdwnstkchg', models.CharField(max_length=100, null=True, blank=True)),
                ('fgldownstk', models.CharField(max_length=100, null=True, blank=True)),
                ('fdownbill', models.CharField(max_length=100, null=True, blank=True)),
                ('fgroupcode', models.CharField(max_length=100, null=True, blank=True)),
                ('fusemetric', models.CharField(max_length=100, null=True, blank=True)),
                ('fgetpalwgt', models.CharField(max_length=100, null=True, blank=True)),
                ('fautowood', models.CharField(max_length=100, null=True, blank=True)),
                ('fcustucc', models.CharField(max_length=100, null=True, blank=True)),
                ('femail', models.CharField(max_length=100, null=True, blank=True)),
                ('fcselyrchg', models.CharField(max_length=100, null=True, blank=True)),
                ('fglcselyr', models.CharField(max_length=100, null=True, blank=True)),
                ('fcountback', models.CharField(max_length=100, null=True, blank=True)),
                ('fdrvrchek', models.CharField(max_length=100, null=True, blank=True)),
                ('fbilltax', models.CharField(max_length=100, null=True, blank=True)),
                ('floadnotes', models.CharField(max_length=100, null=True, blank=True)),
                ('fsap_sto', models.CharField(max_length=100, null=True, blank=True)),
                ('ftunstolod', models.CharField(max_length=100, null=True, blank=True)),
                ('fcpbillopt', models.CharField(max_length=100, null=True, blank=True)),
                ('fhpbasis', models.CharField(max_length=100, null=True, blank=True)),
                ('fhprate', models.CharField(max_length=100, null=True, blank=True)),
                ('fhpgl', models.CharField(max_length=100, null=True, blank=True)),
                ('fhpbilltyp', models.CharField(max_length=100, null=True, blank=True)),
                ('fhpwgttyp', models.CharField(max_length=100, null=True, blank=True)),
                ('faoinvrept', models.CharField(max_length=100, null=True, blank=True)),
                ('fbillprdgp', models.CharField(max_length=100, null=True, blank=True)),
                ('ediconfin', models.CharField(max_length=100, null=True, blank=True)),
                ('fmbolcommt', models.CharField(max_length=100, null=True, blank=True)),
                ('ftunelcros', models.CharField(max_length=100, null=True, blank=True)),
                ('custkey', models.CharField(max_length=40, serialize=False, primary_key=True)),
            ],
            options={
                'db_table': 'mi_customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShipmentMaster',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('newdata', models.IntegerField(null=True, db_column='newData', blank=True)),
                ('facilityid', models.CharField(max_length=10, null=True, db_column='facilityId', blank=True)),
                ('fbatch', models.CharField(max_length=10, null=True, db_column='FBATCH', blank=True)),
                ('fcustcode', models.CharField(max_length=20, null=True, db_column='FCUSTCODE', blank=True)),
                ('floadnum', models.CharField(max_length=20, null=True, db_column='FLOADNUM', blank=True)),
                ('ftrailer', models.CharField(max_length=20, null=True, db_column='FTRAILER', blank=True)),
                ('fdoor', models.CharField(max_length=20, null=True, db_column='FDOOR', blank=True)),
                ('fpurchord', models.CharField(max_length=20, null=True, db_column='FPURCHORD', blank=True)),
                ('fsalesord', models.CharField(max_length=20, null=True, db_column='FSALESORD', blank=True)),
                ('fshipment', models.CharField(max_length=20, null=True, db_column='FSHIPMENT', blank=True)),
                ('fcustbol', models.CharField(max_length=20, null=True, db_column='FCUSTBOL', blank=True)),
                ('fdropnum', models.IntegerField(null=True, db_column='FDROPNUM', blank=True)),
                ('fbdate', models.CharField(max_length=30, null=True, db_column='FBDATE', blank=True)),
                ('forgdeldte', models.CharField(max_length=30, null=True, db_column='FORGDELDTE', blank=True)),
                ('factdeldte', models.CharField(max_length=30, null=True, db_column='FACTDELDTE', blank=True)),
                ('fshipstat', models.CharField(max_length=30, null=True, db_column='FSHIPSTAT', blank=True)),
                ('finuse', models.CharField(max_length=30, null=True, db_column='FINUSE', blank=True)),
                ('fltime', models.CharField(max_length=30, null=True, db_column='FLTIME', blank=True)),
                ('fcrosscust', models.CharField(max_length=30, null=True, db_column='FCROSSCUST', blank=True)),
                ('fconscode', models.CharField(max_length=30, null=True, db_column='FCONSCODE', blank=True)),
                ('fconsignee', models.CharField(max_length=100, null=True, db_column='FCONSIGNEE', blank=True)),
                ('faddress1', models.CharField(max_length=100, null=True, db_column='FADDRESS1', blank=True)),
                ('faddress2', models.CharField(max_length=30, null=True, db_column='FADDRESS2', blank=True)),
                ('fcity', models.CharField(max_length=30, null=True, db_column='FCITY', blank=True)),
                ('fstate', models.CharField(max_length=30, null=True, db_column='FSTATE', blank=True)),
                ('destzip', models.CharField(max_length=30, null=True, db_column='DestZip', blank=True)),
                ('fphone', models.CharField(max_length=30, null=True, db_column='FPHONE', blank=True)),
                ('fseal', models.CharField(max_length=30, null=True, db_column='FSEAL', blank=True)),
                ('carrierid', models.CharField(max_length=30, null=True, db_column='CarrierID', blank=True)),
                ('fcheckqty', models.FloatField(null=True, db_column='FCHECKQTY', blank=True)),
                ('weight', models.FloatField(null=True, db_column='Weight', blank=True)),
                ('totalcube', models.FloatField(null=True, db_column='TotalCube', blank=True)),
                ('fcomment', models.CharField(max_length=100, null=True, db_column='FCOMMENT', blank=True)),
                ('fnotes', models.CharField(max_length=100, null=True, db_column='FNOTES', blank=True)),
                ('ftemp', models.CharField(max_length=100, null=True, db_column='FTEMP', blank=True)),
                ('ffronttemp', models.CharField(max_length=20, null=True, db_column='FFRONTTEMP', blank=True)),
                ('fmidtemp', models.CharField(max_length=20, null=True, db_column='FMIDTEMP', blank=True)),
                ('fbacktemp', models.CharField(max_length=20, null=True, db_column='FBACKTEMP', blank=True)),
                ('fpaymethod', models.CharField(max_length=20, null=True, db_column='FPAYMETHOD', blank=True)),
                ('ftranmeth', models.CharField(max_length=20, null=True, db_column='FTRANMETH', blank=True)),
                ('fmbol', models.CharField(max_length=30, null=True, db_column='FMBOL', blank=True)),
                ('fpickprint', models.CharField(max_length=30, null=True, db_column='FPICKPRINT', blank=True)),
                ('ftrancust', models.CharField(max_length=30, null=True, db_column='FTRANCUST', blank=True)),
                ('fbilldoc', models.CharField(max_length=30, null=True, db_column='FBILLDOC', blank=True)),
                ('ffulpalbil', models.CharField(max_length=30, null=True, db_column='FFULPALBIL', blank=True)),
                ('fcsepckbil', models.CharField(max_length=30, null=True, db_column='FCSEPCKBIL', blank=True)),
                ('flnechrbil', models.CharField(max_length=30, null=True, db_column='FLNECHRBIL', blank=True)),
                ('fexportcty', models.CharField(max_length=30, null=True, db_column='FEXPORTCTY', blank=True)),
                ('fscansttme', models.CharField(max_length=30, null=True, db_column='FSCANSTTME', blank=True)),
                ('fscanstdte', models.CharField(max_length=30, null=True, db_column='FSCANSTDTE', blank=True)),
                ('fscanentme', models.CharField(max_length=30, null=True, db_column='FSCANENTME', blank=True)),
                ('fscanendte', models.CharField(max_length=30, null=True, db_column='FSCANENDTE', blank=True)),
                ('fscanbatch', models.CharField(max_length=30, null=True, db_column='FSCANBATCH', blank=True)),
                ('fscanstat', models.CharField(max_length=30, null=True, db_column='FSCANSTAT', blank=True)),
                ('feditype', models.CharField(max_length=30, null=True, db_column='FEDITYPE', blank=True)),
                ('fedi', models.CharField(max_length=30, null=True, db_column='FEDI', blank=True)),
                ('fedisnddte', models.CharField(max_length=30, null=True, db_column='FEDISNDDTE', blank=True)),
                ('fedisndtme', models.CharField(max_length=30, null=True, db_column='FEDISNDTME', blank=True)),
                ('foedi', models.CharField(max_length=30, null=True, db_column='FOEDI', blank=True)),
                ('foedisdte', models.CharField(max_length=30, null=True, db_column='FOEDISDTE', blank=True)),
                ('foedistme', models.CharField(max_length=30, null=True, db_column='FOEDISTME', blank=True)),
                ('fpalexchng', models.CharField(max_length=30, null=True, db_column='FPALEXCHNG', blank=True)),
                ('fpalcond', models.CharField(max_length=30, null=True, db_column='FPALCOND', blank=True)),
                ('floadoptcd', models.CharField(max_length=30, null=True, db_column='FLOADOPTCD', blank=True)),
                ('fdtecngrsn', models.CharField(max_length=30, null=True, db_column='FDTECNGRSN', blank=True)),
                ('fcarcngrsn', models.CharField(max_length=30, null=True, db_column='FCARCNGRSN', blank=True)),
                ('fversion', models.CharField(max_length=30, null=True, db_column='FVERSION', blank=True)),
                ('fpallets', models.CharField(max_length=30, null=True, db_column='FPALLETS', blank=True)),
                ('fchep', models.CharField(max_length=30, null=True, db_column='FCHEP', blank=True)),
                ('farrivedte', models.CharField(max_length=30, null=True, db_column='FARRIVEDTE', blank=True)),
                ('farrivetme', models.CharField(max_length=30, null=True, db_column='FARRIVETME', blank=True)),
                ('fstartdte', models.CharField(max_length=30, null=True, db_column='FSTARTDTE', blank=True)),
                ('fstarttme', models.CharField(max_length=30, null=True, db_column='FSTARTTME', blank=True)),
                ('ffinishdte', models.CharField(max_length=30, null=True, db_column='FFINISHDTE', blank=True)),
                ('ffinishtme', models.CharField(max_length=30, null=True, db_column='FFINISHTME', blank=True)),
                ('fcolorder', models.CharField(max_length=30, null=True, db_column='FCOLORDER', blank=True)),
                ('fcolwhse', models.CharField(max_length=30, null=True, db_column='FCOLWHSE', blank=True)),
                ('fcolneq', models.CharField(max_length=30, null=True, db_column='FCOLNEQ', blank=True)),
                ('fcolqa', models.CharField(max_length=30, null=True, db_column='FCOLQA', blank=True)),
                ('fcolother', models.CharField(max_length=30, null=True, db_column='FCOLOTHER', blank=True)),
                ('fcolcoment', models.CharField(max_length=30, null=True, db_column='FCOLCOMENT', blank=True)),
                ('ffrzorder', models.CharField(max_length=30, null=True, db_column='FFRZORDER', blank=True)),
                ('ffrzwhse', models.CharField(max_length=30, null=True, db_column='FFRZWHSE', blank=True)),
                ('ffrzneq', models.CharField(max_length=30, null=True, db_column='FFRZNEQ', blank=True)),
                ('ffrzqa', models.CharField(max_length=30, null=True, db_column='FFRZQA', blank=True)),
                ('ffrzother', models.CharField(max_length=30, null=True, db_column='FFRZOTHER', blank=True)),
                ('ffrzcoment', models.CharField(max_length=30, null=True, db_column='FFRZCOMENT', blank=True)),
                ('fdryorder', models.CharField(max_length=30, null=True, db_column='FDRYORDER', blank=True)),
                ('fdrywhse', models.CharField(max_length=30, null=True, db_column='FDRYWHSE', blank=True)),
                ('fdryneq', models.CharField(max_length=30, null=True, db_column='FDRYNEQ', blank=True)),
                ('fdryqa', models.CharField(max_length=30, null=True, db_column='FDRYQA', blank=True)),
                ('fdryother', models.CharField(max_length=30, null=True, db_column='FDRYOTHER', blank=True)),
                ('fdrycoment', models.CharField(max_length=30, null=True, db_column='FDRYCOMENT', blank=True)),
                ('fconfirmnm', models.CharField(max_length=30, null=True, db_column='FCONFIRMNM', blank=True)),
                ('flivedrop', models.CharField(max_length=30, null=True, db_column='FLIVEDROP', blank=True)),
                ('fschcoment', models.CharField(max_length=30, null=True, db_column='FSCHCOMENT', blank=True)),
                ('fsignoutme', models.CharField(max_length=30, null=True, db_column='FSIGNOUTME', blank=True)),
                ('fsignoudte', models.CharField(max_length=30, null=True, db_column='FSIGNOUDTE', blank=True)),
                ('fdriver', models.CharField(max_length=30, null=True, db_column='FDRIVER', blank=True)),
                ('fplanned', models.CharField(max_length=30, null=True, db_column='FPLANNED', blank=True)),
                ('fwho', models.CharField(max_length=30, null=True, db_column='FWHO', blank=True)),
                ('fdatestamp', models.CharField(max_length=30, null=True, db_column='FDATESTAMP', blank=True)),
                ('ftimestamp', models.CharField(max_length=30, null=True, db_column='FTIMESTAMP', blank=True)),
                ('fwhoship', models.CharField(max_length=30, null=True, db_column='FWHOSHIP', blank=True)),
                ('fshipdate', models.CharField(max_length=30, null=True, db_column='FSHIPDATE', blank=True)),
                ('fshiptime', models.CharField(max_length=30, null=True, db_column='FSHIPTIME', blank=True)),
                ('fedipick', models.CharField(max_length=30, null=True, db_column='FEDIPICK', blank=True)),
                ('fconfwhen', models.CharField(max_length=30, null=True, db_column='FCONFWHEN', blank=True)),
                ('fconfwho', models.CharField(max_length=30, null=True, db_column='FCONFWHO', blank=True)),
                ('fpickwho', models.CharField(max_length=30, null=True, db_column='FPICKWHO', blank=True)),
                ('fpickdte', models.CharField(max_length=30, null=True, db_column='FPICKDTE', blank=True)),
                ('fchepcust', models.CharField(max_length=30, null=True, db_column='FCHEPCUST', blank=True)),
                ('fcedi', models.CharField(max_length=30, null=True, db_column='FCEDI', blank=True)),
                ('fcedisdte', models.CharField(max_length=30, null=True, db_column='FCEDISDTE', blank=True)),
                ('fcedistme', models.CharField(max_length=30, null=True, db_column='FCEDISTME', blank=True)),
                ('fgroupcode', models.CharField(max_length=30, null=True, db_column='FGROUPCODE', blank=True)),
                ('fsig', models.CharField(max_length=30, null=True, db_column='FSIG', blank=True)),
                ('fcpc', models.CharField(max_length=30, null=True, db_column='FCPC', blank=True)),
                ('fchedi', models.CharField(max_length=30, null=True, db_column='FCHEDI', blank=True)),
                ('fchedisdte', models.CharField(max_length=30, null=True, db_column='FCHEDISDTE', blank=True)),
                ('fchedistme', models.CharField(max_length=30, null=True, db_column='FCHEDISTME', blank=True)),
                ('finbatch', models.CharField(max_length=30, null=True, db_column='FINBATCH', blank=True)),
                ('flabeltype', models.CharField(max_length=30, null=True, db_column='FLABELTYPE', blank=True)),
                ('forgsched', models.CharField(max_length=30, null=True, db_column='FORGSCHED', blank=True)),
                ('fcrtebymod', models.CharField(max_length=30, null=True, db_column='FCRTEBYMOD', blank=True)),
                ('fpalreq', models.CharField(max_length=30, null=True, db_column='FPALREQ', blank=True)),
                ('fchepreq', models.CharField(max_length=30, null=True, db_column='FCHEPREQ', blank=True)),
                ('fcpcreq', models.CharField(max_length=30, null=True, db_column='FCPCREQ', blank=True)),
                ('fothreq', models.CharField(max_length=30, null=True, db_column='FOTHREQ', blank=True)),
                ('ftempovr', models.CharField(max_length=30, null=True, db_column='FTEMPOVR', blank=True)),
                ('figpsreq', models.CharField(max_length=30, null=True, db_column='FIGPSREQ', blank=True)),
                ('figps', models.CharField(max_length=30, null=True, db_column='FIGPS', blank=True)),
                ('fcustdata', models.CharField(max_length=30, null=True, db_column='FCUSTDATA', blank=True)),
                ('ftmphppzne', models.CharField(max_length=30, null=True, db_column='FTMPHPPZNE', blank=True)),
                ('custkey', models.CharField(max_length=40, null=True, blank=True)),
                ('datedt', models.DateTimeField(null=True, db_column='dateDT', blank=True)),
            ],
            options={
                'db_table': 'shipment_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShipmentMasterIntermediate',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('newdata', models.IntegerField(null=True, db_column='newData', blank=True)),
                ('facilityid', models.CharField(max_length=10, null=True, db_column='facilityId', blank=True)),
                ('fbatch', models.CharField(max_length=10, null=True, db_column='FBATCH', blank=True)),
                ('fcustcode', models.CharField(max_length=20, null=True, db_column='FCUSTCODE', blank=True)),
                ('floadnum', models.CharField(max_length=20, null=True, db_column='FLOADNUM', blank=True)),
                ('ftrailer', models.CharField(max_length=20, null=True, db_column='FTRAILER', blank=True)),
                ('fdoor', models.CharField(max_length=20, null=True, db_column='FDOOR', blank=True)),
                ('fpurchord', models.CharField(max_length=20, null=True, db_column='FPURCHORD', blank=True)),
                ('fsalesord', models.CharField(max_length=20, null=True, db_column='FSALESORD', blank=True)),
                ('fshipment', models.CharField(max_length=20, null=True, db_column='FSHIPMENT', blank=True)),
                ('fcustbol', models.CharField(max_length=20, null=True, db_column='FCUSTBOL', blank=True)),
                ('fdropnum', models.IntegerField(null=True, db_column='FDROPNUM', blank=True)),
                ('fbdate', models.CharField(max_length=30, null=True, db_column='FBDATE', blank=True)),
                ('forgdeldte', models.CharField(max_length=30, null=True, db_column='FORGDELDTE', blank=True)),
                ('factdeldte', models.CharField(max_length=30, null=True, db_column='FACTDELDTE', blank=True)),
                ('fshipstat', models.CharField(max_length=30, null=True, db_column='FSHIPSTAT', blank=True)),
                ('finuse', models.CharField(max_length=30, null=True, db_column='FINUSE', blank=True)),
                ('fltime', models.CharField(max_length=30, null=True, db_column='FLTIME', blank=True)),
                ('fcrosscust', models.CharField(max_length=30, null=True, db_column='FCROSSCUST', blank=True)),
                ('fconscode', models.CharField(max_length=30, null=True, db_column='FCONSCODE', blank=True)),
                ('fconsignee', models.CharField(max_length=100, null=True, db_column='FCONSIGNEE', blank=True)),
                ('faddress1', models.CharField(max_length=100, null=True, db_column='FADDRESS1', blank=True)),
                ('faddress2', models.CharField(max_length=30, null=True, db_column='FADDRESS2', blank=True)),
                ('fcity', models.CharField(max_length=30, null=True, db_column='FCITY', blank=True)),
                ('fstate', models.CharField(max_length=30, null=True, db_column='FSTATE', blank=True)),
                ('destzip', models.CharField(max_length=30, null=True, db_column='DestZip', blank=True)),
                ('fphone', models.CharField(max_length=30, null=True, db_column='FPHONE', blank=True)),
                ('fseal', models.CharField(max_length=30, null=True, db_column='FSEAL', blank=True)),
                ('carrierid', models.CharField(max_length=30, null=True, db_column='CarrierID', blank=True)),
                ('fcheckqty', models.FloatField(null=True, db_column='FCHECKQTY', blank=True)),
                ('weight', models.FloatField(null=True, db_column='Weight', blank=True)),
                ('totalcube', models.FloatField(null=True, db_column='TotalCube', blank=True)),
                ('fcomment', models.CharField(max_length=100, null=True, db_column='FCOMMENT', blank=True)),
                ('fnotes', models.CharField(max_length=100, null=True, db_column='FNOTES', blank=True)),
                ('ftemp', models.CharField(max_length=100, null=True, db_column='FTEMP', blank=True)),
                ('ffronttemp', models.CharField(max_length=20, null=True, db_column='FFRONTTEMP', blank=True)),
                ('fmidtemp', models.CharField(max_length=20, null=True, db_column='FMIDTEMP', blank=True)),
                ('fbacktemp', models.CharField(max_length=20, null=True, db_column='FBACKTEMP', blank=True)),
                ('fpaymethod', models.CharField(max_length=20, null=True, db_column='FPAYMETHOD', blank=True)),
                ('ftranmeth', models.CharField(max_length=20, null=True, db_column='FTRANMETH', blank=True)),
                ('fmbol', models.CharField(max_length=30, null=True, db_column='FMBOL', blank=True)),
                ('fpickprint', models.CharField(max_length=30, null=True, db_column='FPICKPRINT', blank=True)),
                ('ftrancust', models.CharField(max_length=30, null=True, db_column='FTRANCUST', blank=True)),
                ('fbilldoc', models.CharField(max_length=30, null=True, db_column='FBILLDOC', blank=True)),
                ('ffulpalbil', models.CharField(max_length=30, null=True, db_column='FFULPALBIL', blank=True)),
                ('fcsepckbil', models.CharField(max_length=30, null=True, db_column='FCSEPCKBIL', blank=True)),
                ('flnechrbil', models.CharField(max_length=30, null=True, db_column='FLNECHRBIL', blank=True)),
                ('fexportcty', models.CharField(max_length=30, null=True, db_column='FEXPORTCTY', blank=True)),
                ('fscansttme', models.CharField(max_length=30, null=True, db_column='FSCANSTTME', blank=True)),
                ('fscanstdte', models.CharField(max_length=30, null=True, db_column='FSCANSTDTE', blank=True)),
                ('fscanentme', models.CharField(max_length=30, null=True, db_column='FSCANENTME', blank=True)),
                ('fscanendte', models.CharField(max_length=30, null=True, db_column='FSCANENDTE', blank=True)),
                ('fscanbatch', models.CharField(max_length=30, null=True, db_column='FSCANBATCH', blank=True)),
                ('fscanstat', models.CharField(max_length=30, null=True, db_column='FSCANSTAT', blank=True)),
                ('feditype', models.CharField(max_length=30, null=True, db_column='FEDITYPE', blank=True)),
                ('fedi', models.CharField(max_length=30, null=True, db_column='FEDI', blank=True)),
                ('fedisnddte', models.CharField(max_length=30, null=True, db_column='FEDISNDDTE', blank=True)),
                ('fedisndtme', models.CharField(max_length=30, null=True, db_column='FEDISNDTME', blank=True)),
                ('foedi', models.CharField(max_length=30, null=True, db_column='FOEDI', blank=True)),
                ('foedisdte', models.CharField(max_length=30, null=True, db_column='FOEDISDTE', blank=True)),
                ('foedistme', models.CharField(max_length=30, null=True, db_column='FOEDISTME', blank=True)),
                ('fpalexchng', models.CharField(max_length=30, null=True, db_column='FPALEXCHNG', blank=True)),
                ('fpalcond', models.CharField(max_length=30, null=True, db_column='FPALCOND', blank=True)),
                ('floadoptcd', models.CharField(max_length=30, null=True, db_column='FLOADOPTCD', blank=True)),
                ('fdtecngrsn', models.CharField(max_length=30, null=True, db_column='FDTECNGRSN', blank=True)),
                ('fcarcngrsn', models.CharField(max_length=30, null=True, db_column='FCARCNGRSN', blank=True)),
                ('fversion', models.CharField(max_length=30, null=True, db_column='FVERSION', blank=True)),
                ('fpallets', models.CharField(max_length=30, null=True, db_column='FPALLETS', blank=True)),
                ('fchep', models.CharField(max_length=30, null=True, db_column='FCHEP', blank=True)),
                ('farrivedte', models.CharField(max_length=30, null=True, db_column='FARRIVEDTE', blank=True)),
                ('farrivetme', models.CharField(max_length=30, null=True, db_column='FARRIVETME', blank=True)),
                ('fstartdte', models.CharField(max_length=30, null=True, db_column='FSTARTDTE', blank=True)),
                ('fstarttme', models.CharField(max_length=30, null=True, db_column='FSTARTTME', blank=True)),
                ('ffinishdte', models.CharField(max_length=30, null=True, db_column='FFINISHDTE', blank=True)),
                ('ffinishtme', models.CharField(max_length=30, null=True, db_column='FFINISHTME', blank=True)),
                ('fcolorder', models.CharField(max_length=30, null=True, db_column='FCOLORDER', blank=True)),
                ('fcolwhse', models.CharField(max_length=30, null=True, db_column='FCOLWHSE', blank=True)),
                ('fcolneq', models.CharField(max_length=30, null=True, db_column='FCOLNEQ', blank=True)),
                ('fcolqa', models.CharField(max_length=30, null=True, db_column='FCOLQA', blank=True)),
                ('fcolother', models.CharField(max_length=30, null=True, db_column='FCOLOTHER', blank=True)),
                ('fcolcoment', models.CharField(max_length=30, null=True, db_column='FCOLCOMENT', blank=True)),
                ('ffrzorder', models.CharField(max_length=30, null=True, db_column='FFRZORDER', blank=True)),
                ('ffrzwhse', models.CharField(max_length=30, null=True, db_column='FFRZWHSE', blank=True)),
                ('ffrzneq', models.CharField(max_length=30, null=True, db_column='FFRZNEQ', blank=True)),
                ('ffrzqa', models.CharField(max_length=30, null=True, db_column='FFRZQA', blank=True)),
                ('ffrzother', models.CharField(max_length=30, null=True, db_column='FFRZOTHER', blank=True)),
                ('ffrzcoment', models.CharField(max_length=30, null=True, db_column='FFRZCOMENT', blank=True)),
                ('fdryorder', models.CharField(max_length=30, null=True, db_column='FDRYORDER', blank=True)),
                ('fdrywhse', models.CharField(max_length=30, null=True, db_column='FDRYWHSE', blank=True)),
                ('fdryneq', models.CharField(max_length=30, null=True, db_column='FDRYNEQ', blank=True)),
                ('fdryqa', models.CharField(max_length=30, null=True, db_column='FDRYQA', blank=True)),
                ('fdryother', models.CharField(max_length=30, null=True, db_column='FDRYOTHER', blank=True)),
                ('fdrycoment', models.CharField(max_length=30, null=True, db_column='FDRYCOMENT', blank=True)),
                ('fconfirmnm', models.CharField(max_length=30, null=True, db_column='FCONFIRMNM', blank=True)),
                ('flivedrop', models.CharField(max_length=30, null=True, db_column='FLIVEDROP', blank=True)),
                ('fschcoment', models.CharField(max_length=30, null=True, db_column='FSCHCOMENT', blank=True)),
                ('fsignoutme', models.CharField(max_length=30, null=True, db_column='FSIGNOUTME', blank=True)),
                ('fsignoudte', models.CharField(max_length=30, null=True, db_column='FSIGNOUDTE', blank=True)),
                ('fdriver', models.CharField(max_length=30, null=True, db_column='FDRIVER', blank=True)),
                ('fplanned', models.CharField(max_length=30, null=True, db_column='FPLANNED', blank=True)),
                ('fwho', models.CharField(max_length=30, null=True, db_column='FWHO', blank=True)),
                ('fdatestamp', models.CharField(max_length=30, null=True, db_column='FDATESTAMP', blank=True)),
                ('ftimestamp', models.CharField(max_length=30, null=True, db_column='FTIMESTAMP', blank=True)),
                ('fwhoship', models.CharField(max_length=30, null=True, db_column='FWHOSHIP', blank=True)),
                ('fshipdate', models.CharField(max_length=30, null=True, db_column='FSHIPDATE', blank=True)),
                ('fshiptime', models.CharField(max_length=30, null=True, db_column='FSHIPTIME', blank=True)),
                ('fedipick', models.CharField(max_length=30, null=True, db_column='FEDIPICK', blank=True)),
                ('fconfwhen', models.CharField(max_length=30, null=True, db_column='FCONFWHEN', blank=True)),
                ('fconfwho', models.CharField(max_length=30, null=True, db_column='FCONFWHO', blank=True)),
                ('fpickwho', models.CharField(max_length=30, null=True, db_column='FPICKWHO', blank=True)),
                ('fpickdte', models.CharField(max_length=30, null=True, db_column='FPICKDTE', blank=True)),
                ('fchepcust', models.CharField(max_length=30, null=True, db_column='FCHEPCUST', blank=True)),
                ('fcedi', models.CharField(max_length=30, null=True, db_column='FCEDI', blank=True)),
                ('fcedisdte', models.CharField(max_length=30, null=True, db_column='FCEDISDTE', blank=True)),
                ('fcedistme', models.CharField(max_length=30, null=True, db_column='FCEDISTME', blank=True)),
                ('fgroupcode', models.CharField(max_length=30, null=True, db_column='FGROUPCODE', blank=True)),
                ('fsig', models.CharField(max_length=30, null=True, db_column='FSIG', blank=True)),
                ('fcpc', models.CharField(max_length=30, null=True, db_column='FCPC', blank=True)),
                ('fchedi', models.CharField(max_length=30, null=True, db_column='FCHEDI', blank=True)),
                ('fchedisdte', models.CharField(max_length=30, null=True, db_column='FCHEDISDTE', blank=True)),
                ('fchedistme', models.CharField(max_length=30, null=True, db_column='FCHEDISTME', blank=True)),
                ('finbatch', models.CharField(max_length=30, null=True, db_column='FINBATCH', blank=True)),
                ('flabeltype', models.CharField(max_length=30, null=True, db_column='FLABELTYPE', blank=True)),
                ('forgsched', models.CharField(max_length=30, null=True, db_column='FORGSCHED', blank=True)),
                ('fcrtebymod', models.CharField(max_length=30, null=True, db_column='FCRTEBYMOD', blank=True)),
                ('fpalreq', models.CharField(max_length=30, null=True, db_column='FPALREQ', blank=True)),
                ('fchepreq', models.CharField(max_length=30, null=True, db_column='FCHEPREQ', blank=True)),
                ('fcpcreq', models.CharField(max_length=30, null=True, db_column='FCPCREQ', blank=True)),
                ('fothreq', models.CharField(max_length=30, null=True, db_column='FOTHREQ', blank=True)),
                ('ftempovr', models.CharField(max_length=30, null=True, db_column='FTEMPOVR', blank=True)),
                ('figpsreq', models.CharField(max_length=30, null=True, db_column='FIGPSREQ', blank=True)),
                ('figps', models.CharField(max_length=30, null=True, db_column='FIGPS', blank=True)),
                ('fcustdata', models.CharField(max_length=30, null=True, db_column='FCUSTDATA', blank=True)),
                ('ftmphppzne', models.CharField(max_length=30, null=True, db_column='FTMPHPPZNE', blank=True)),
                ('custkey', models.CharField(max_length=40, null=True, blank=True)),
                ('datedt', models.DateTimeField(null=True, db_column='dateDT', blank=True)),
                ('originzip', models.CharField(max_length=20, null=True, db_column='OriginZip', blank=True)),
                ('custname', models.CharField(max_length=100, null=True, db_column='custName', blank=True)),
            ],
            options={
                'db_table': 'shipment_master_intermediate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShipmentMasterLatLon',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('newdata', models.IntegerField(null=True, db_column='newData', blank=True)),
                ('facilityid', models.CharField(max_length=10, null=True, db_column='facilityId', blank=True)),
                ('fbatch', models.CharField(max_length=10, null=True, db_column='FBATCH', blank=True)),
                ('fcustcode', models.CharField(max_length=20, null=True, db_column='FCUSTCODE', blank=True)),
                ('floadnum', models.CharField(max_length=20, null=True, db_column='FLOADNUM', blank=True)),
                ('ftrailer', models.CharField(max_length=20, null=True, db_column='FTRAILER', blank=True)),
                ('fdoor', models.CharField(max_length=20, null=True, db_column='FDOOR', blank=True)),
                ('fpurchord', models.CharField(max_length=20, null=True, db_column='FPURCHORD', blank=True)),
                ('fsalesord', models.CharField(max_length=20, null=True, db_column='FSALESORD', blank=True)),
                ('fshipment', models.CharField(max_length=20, null=True, db_column='FSHIPMENT', blank=True)),
                ('fcustbol', models.CharField(max_length=20, null=True, db_column='FCUSTBOL', blank=True)),
                ('fdropnum', models.IntegerField(null=True, db_column='FDROPNUM', blank=True)),
                ('fbdate', models.CharField(max_length=30, null=True, db_column='FBDATE', blank=True)),
                ('forgdeldte', models.CharField(max_length=30, null=True, db_column='FORGDELDTE', blank=True)),
                ('factdeldte', models.CharField(max_length=30, null=True, db_column='FACTDELDTE', blank=True)),
                ('fshipstat', models.CharField(max_length=30, null=True, db_column='FSHIPSTAT', blank=True)),
                ('finuse', models.CharField(max_length=30, null=True, db_column='FINUSE', blank=True)),
                ('fltime', models.CharField(max_length=30, null=True, db_column='FLTIME', blank=True)),
                ('fcrosscust', models.CharField(max_length=30, null=True, db_column='FCROSSCUST', blank=True)),
                ('fconscode', models.CharField(max_length=30, null=True, db_column='FCONSCODE', blank=True)),
                ('fconsignee', models.CharField(max_length=100, null=True, db_column='FCONSIGNEE', blank=True)),
                ('faddress1', models.CharField(max_length=100, null=True, db_column='FADDRESS1', blank=True)),
                ('faddress2', models.CharField(max_length=30, null=True, db_column='FADDRESS2', blank=True)),
                ('fcity', models.CharField(max_length=30, null=True, db_column='FCITY', blank=True)),
                ('fstate', models.CharField(max_length=30, null=True, db_column='FSTATE', blank=True)),
                ('destzip', models.CharField(max_length=30, null=True, db_column='DestZip', blank=True)),
                ('fphone', models.CharField(max_length=30, null=True, db_column='FPHONE', blank=True)),
                ('fseal', models.CharField(max_length=30, null=True, db_column='FSEAL', blank=True)),
                ('carrierid', models.CharField(max_length=30, null=True, db_column='CarrierID', blank=True)),
                ('fcheckqty', models.FloatField(null=True, db_column='FCHECKQTY', blank=True)),
                ('weight', models.FloatField(null=True, db_column='Weight', blank=True)),
                ('totalcube', models.FloatField(null=True, db_column='TotalCube', blank=True)),
                ('fcomment', models.CharField(max_length=100, null=True, db_column='FCOMMENT', blank=True)),
                ('fnotes', models.CharField(max_length=100, null=True, db_column='FNOTES', blank=True)),
                ('ftemp', models.CharField(max_length=100, null=True, db_column='FTEMP', blank=True)),
                ('ffronttemp', models.CharField(max_length=20, null=True, db_column='FFRONTTEMP', blank=True)),
                ('fmidtemp', models.CharField(max_length=20, null=True, db_column='FMIDTEMP', blank=True)),
                ('fbacktemp', models.CharField(max_length=20, null=True, db_column='FBACKTEMP', blank=True)),
                ('fpaymethod', models.CharField(max_length=20, null=True, db_column='FPAYMETHOD', blank=True)),
                ('ftranmeth', models.CharField(max_length=20, null=True, db_column='FTRANMETH', blank=True)),
                ('fmbol', models.CharField(max_length=30, null=True, db_column='FMBOL', blank=True)),
                ('fpickprint', models.CharField(max_length=30, null=True, db_column='FPICKPRINT', blank=True)),
                ('ftrancust', models.CharField(max_length=30, null=True, db_column='FTRANCUST', blank=True)),
                ('fbilldoc', models.CharField(max_length=30, null=True, db_column='FBILLDOC', blank=True)),
                ('ffulpalbil', models.CharField(max_length=30, null=True, db_column='FFULPALBIL', blank=True)),
                ('fcsepckbil', models.CharField(max_length=30, null=True, db_column='FCSEPCKBIL', blank=True)),
                ('flnechrbil', models.CharField(max_length=30, null=True, db_column='FLNECHRBIL', blank=True)),
                ('fexportcty', models.CharField(max_length=30, null=True, db_column='FEXPORTCTY', blank=True)),
                ('fscansttme', models.CharField(max_length=30, null=True, db_column='FSCANSTTME', blank=True)),
                ('fscanstdte', models.CharField(max_length=30, null=True, db_column='FSCANSTDTE', blank=True)),
                ('fscanentme', models.CharField(max_length=30, null=True, db_column='FSCANENTME', blank=True)),
                ('fscanendte', models.CharField(max_length=30, null=True, db_column='FSCANENDTE', blank=True)),
                ('fscanbatch', models.CharField(max_length=30, null=True, db_column='FSCANBATCH', blank=True)),
                ('fscanstat', models.CharField(max_length=30, null=True, db_column='FSCANSTAT', blank=True)),
                ('feditype', models.CharField(max_length=30, null=True, db_column='FEDITYPE', blank=True)),
                ('fedi', models.CharField(max_length=30, null=True, db_column='FEDI', blank=True)),
                ('fedisnddte', models.CharField(max_length=30, null=True, db_column='FEDISNDDTE', blank=True)),
                ('fedisndtme', models.CharField(max_length=30, null=True, db_column='FEDISNDTME', blank=True)),
                ('foedi', models.CharField(max_length=30, null=True, db_column='FOEDI', blank=True)),
                ('foedisdte', models.CharField(max_length=30, null=True, db_column='FOEDISDTE', blank=True)),
                ('foedistme', models.CharField(max_length=30, null=True, db_column='FOEDISTME', blank=True)),
                ('fpalexchng', models.CharField(max_length=30, null=True, db_column='FPALEXCHNG', blank=True)),
                ('fpalcond', models.CharField(max_length=30, null=True, db_column='FPALCOND', blank=True)),
                ('floadoptcd', models.CharField(max_length=30, null=True, db_column='FLOADOPTCD', blank=True)),
                ('fdtecngrsn', models.CharField(max_length=30, null=True, db_column='FDTECNGRSN', blank=True)),
                ('fcarcngrsn', models.CharField(max_length=30, null=True, db_column='FCARCNGRSN', blank=True)),
                ('fversion', models.CharField(max_length=30, null=True, db_column='FVERSION', blank=True)),
                ('fpallets', models.CharField(max_length=30, null=True, db_column='FPALLETS', blank=True)),
                ('fchep', models.CharField(max_length=30, null=True, db_column='FCHEP', blank=True)),
                ('farrivedte', models.CharField(max_length=30, null=True, db_column='FARRIVEDTE', blank=True)),
                ('farrivetme', models.CharField(max_length=30, null=True, db_column='FARRIVETME', blank=True)),
                ('fstartdte', models.CharField(max_length=30, null=True, db_column='FSTARTDTE', blank=True)),
                ('fstarttme', models.CharField(max_length=30, null=True, db_column='FSTARTTME', blank=True)),
                ('ffinishdte', models.CharField(max_length=30, null=True, db_column='FFINISHDTE', blank=True)),
                ('ffinishtme', models.CharField(max_length=30, null=True, db_column='FFINISHTME', blank=True)),
                ('fcolorder', models.CharField(max_length=30, null=True, db_column='FCOLORDER', blank=True)),
                ('fcolwhse', models.CharField(max_length=30, null=True, db_column='FCOLWHSE', blank=True)),
                ('fcolneq', models.CharField(max_length=30, null=True, db_column='FCOLNEQ', blank=True)),
                ('fcolqa', models.CharField(max_length=30, null=True, db_column='FCOLQA', blank=True)),
                ('fcolother', models.CharField(max_length=30, null=True, db_column='FCOLOTHER', blank=True)),
                ('fcolcoment', models.CharField(max_length=30, null=True, db_column='FCOLCOMENT', blank=True)),
                ('ffrzorder', models.CharField(max_length=30, null=True, db_column='FFRZORDER', blank=True)),
                ('ffrzwhse', models.CharField(max_length=30, null=True, db_column='FFRZWHSE', blank=True)),
                ('ffrzneq', models.CharField(max_length=30, null=True, db_column='FFRZNEQ', blank=True)),
                ('ffrzqa', models.CharField(max_length=30, null=True, db_column='FFRZQA', blank=True)),
                ('ffrzother', models.CharField(max_length=30, null=True, db_column='FFRZOTHER', blank=True)),
                ('ffrzcoment', models.CharField(max_length=30, null=True, db_column='FFRZCOMENT', blank=True)),
                ('fdryorder', models.CharField(max_length=30, null=True, db_column='FDRYORDER', blank=True)),
                ('fdrywhse', models.CharField(max_length=30, null=True, db_column='FDRYWHSE', blank=True)),
                ('fdryneq', models.CharField(max_length=30, null=True, db_column='FDRYNEQ', blank=True)),
                ('fdryqa', models.CharField(max_length=30, null=True, db_column='FDRYQA', blank=True)),
                ('fdryother', models.CharField(max_length=30, null=True, db_column='FDRYOTHER', blank=True)),
                ('fdrycoment', models.CharField(max_length=30, null=True, db_column='FDRYCOMENT', blank=True)),
                ('fconfirmnm', models.CharField(max_length=30, null=True, db_column='FCONFIRMNM', blank=True)),
                ('flivedrop', models.CharField(max_length=30, null=True, db_column='FLIVEDROP', blank=True)),
                ('fschcoment', models.CharField(max_length=30, null=True, db_column='FSCHCOMENT', blank=True)),
                ('fsignoutme', models.CharField(max_length=30, null=True, db_column='FSIGNOUTME', blank=True)),
                ('fsignoudte', models.CharField(max_length=30, null=True, db_column='FSIGNOUDTE', blank=True)),
                ('fdriver', models.CharField(max_length=30, null=True, db_column='FDRIVER', blank=True)),
                ('fplanned', models.CharField(max_length=30, null=True, db_column='FPLANNED', blank=True)),
                ('fwho', models.CharField(max_length=30, null=True, db_column='FWHO', blank=True)),
                ('fdatestamp', models.CharField(max_length=30, null=True, db_column='FDATESTAMP', blank=True)),
                ('ftimestamp', models.CharField(max_length=30, null=True, db_column='FTIMESTAMP', blank=True)),
                ('fwhoship', models.CharField(max_length=30, null=True, db_column='FWHOSHIP', blank=True)),
                ('fshipdate', models.CharField(max_length=30, null=True, db_column='FSHIPDATE', blank=True)),
                ('fshiptime', models.CharField(max_length=30, null=True, db_column='FSHIPTIME', blank=True)),
                ('fedipick', models.CharField(max_length=30, null=True, db_column='FEDIPICK', blank=True)),
                ('fconfwhen', models.CharField(max_length=30, null=True, db_column='FCONFWHEN', blank=True)),
                ('fconfwho', models.CharField(max_length=30, null=True, db_column='FCONFWHO', blank=True)),
                ('fpickwho', models.CharField(max_length=30, null=True, db_column='FPICKWHO', blank=True)),
                ('fpickdte', models.CharField(max_length=30, null=True, db_column='FPICKDTE', blank=True)),
                ('fchepcust', models.CharField(max_length=30, null=True, db_column='FCHEPCUST', blank=True)),
                ('fcedi', models.CharField(max_length=30, null=True, db_column='FCEDI', blank=True)),
                ('fcedisdte', models.CharField(max_length=30, null=True, db_column='FCEDISDTE', blank=True)),
                ('fcedistme', models.CharField(max_length=30, null=True, db_column='FCEDISTME', blank=True)),
                ('fgroupcode', models.CharField(max_length=30, null=True, db_column='FGROUPCODE', blank=True)),
                ('fsig', models.CharField(max_length=30, null=True, db_column='FSIG', blank=True)),
                ('fcpc', models.CharField(max_length=30, null=True, db_column='FCPC', blank=True)),
                ('fchedi', models.CharField(max_length=30, null=True, db_column='FCHEDI', blank=True)),
                ('fchedisdte', models.CharField(max_length=30, null=True, db_column='FCHEDISDTE', blank=True)),
                ('fchedistme', models.CharField(max_length=30, null=True, db_column='FCHEDISTME', blank=True)),
                ('finbatch', models.CharField(max_length=30, null=True, db_column='FINBATCH', blank=True)),
                ('flabeltype', models.CharField(max_length=30, null=True, db_column='FLABELTYPE', blank=True)),
                ('forgsched', models.CharField(max_length=30, null=True, db_column='FORGSCHED', blank=True)),
                ('fcrtebymod', models.CharField(max_length=30, null=True, db_column='FCRTEBYMOD', blank=True)),
                ('fpalreq', models.CharField(max_length=30, null=True, db_column='FPALREQ', blank=True)),
                ('fchepreq', models.CharField(max_length=30, null=True, db_column='FCHEPREQ', blank=True)),
                ('fcpcreq', models.CharField(max_length=30, null=True, db_column='FCPCREQ', blank=True)),
                ('fothreq', models.CharField(max_length=30, null=True, db_column='FOTHREQ', blank=True)),
                ('ftempovr', models.CharField(max_length=30, null=True, db_column='FTEMPOVR', blank=True)),
                ('figpsreq', models.CharField(max_length=30, null=True, db_column='FIGPSREQ', blank=True)),
                ('figps', models.CharField(max_length=30, null=True, db_column='FIGPS', blank=True)),
                ('fcustdata', models.CharField(max_length=30, null=True, db_column='FCUSTDATA', blank=True)),
                ('ftmphppzne', models.CharField(max_length=30, null=True, db_column='FTMPHPPZNE', blank=True)),
                ('custkey', models.CharField(max_length=40, null=True, blank=True)),
                ('datedt', models.DateTimeField(null=True, db_column='dateDT', blank=True)),
                ('originzip', models.CharField(max_length=20, null=True, db_column='OriginZip', blank=True)),
                ('custname', models.CharField(max_length=100, null=True, db_column='custName', blank=True)),
                ('origin_lat', models.FloatField(null=True, blank=True)),
                ('origin_lon', models.FloatField(null=True, blank=True)),
                ('origin_std_city', models.CharField(max_length=100, null=True, blank=True)),
                ('origin_std_state', models.CharField(max_length=20, null=True, blank=True)),
                ('origin_coord_name', models.CharField(max_length=100, null=True, blank=True)),
                ('dest_lat', models.FloatField(null=True, blank=True)),
                ('dest_lon', models.FloatField(null=True, blank=True)),
                ('dest_std_city', models.CharField(max_length=100, null=True, blank=True)),
                ('dest_std_state', models.CharField(max_length=20, null=True, blank=True)),
                ('dest_coord_name', models.CharField(max_length=100, null=True, blank=True)),
                ('overlap', models.IntegerField()),
                ('carriername', models.CharField(max_length=100, null=True, db_column='carrierName', blank=True)),
            ],
            options={
                'db_table': 'shipment_master_lat_lon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Warehouses',
            fields=[
                ('prefix', models.CharField(max_length=10, null=True, blank=True)),
                ('native', models.CharField(max_length=20, null=True, blank=True)),
                ('whid', models.CharField(max_length=20, null=True, blank=True)),
                ('whname', models.CharField(max_length=100, null=True, blank=True)),
                ('addr1', models.CharField(max_length=100, null=True, blank=True)),
                ('addr2', models.CharField(max_length=100, null=True, blank=True)),
                ('addr3', models.CharField(max_length=100, null=True, blank=True)),
                ('city', models.CharField(max_length=100, null=True, blank=True)),
                ('state', models.CharField(max_length=20, null=True, blank=True)),
                ('zip', models.CharField(max_length=20, null=True, blank=True)),
                ('phone', models.CharField(max_length=30, null=True, blank=True)),
                ('fax', models.CharField(max_length=30, null=True, blank=True)),
                ('country_code', models.CharField(max_length=10, null=True, blank=True)),
                ('whid_join', models.CharField(max_length=10, serialize=False, primary_key=True)),
            ],
            options={
                'db_table': 'warehouses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zips',
            fields=[
                ('zip', models.CharField(max_length=10, serialize=False, primary_key=True)),
                ('city', models.CharField(max_length=100, null=True, blank=True)),
                ('state', models.CharField(max_length=20, null=True, blank=True)),
                ('lat', models.FloatField(null=True, blank=True)),
                ('lon', models.FloatField(null=True, blank=True)),
                ('timezone', models.FloatField(null=True, blank=True)),
                ('dst', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'zips',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zips2',
            fields=[
                ('zip', models.CharField(max_length=10, serialize=False, primary_key=True)),
                ('city', models.CharField(max_length=100, null=True, blank=True)),
                ('state', models.CharField(max_length=20, null=True, blank=True)),
                ('lat', models.FloatField(null=True, blank=True)),
                ('lon', models.FloatField(null=True, blank=True)),
                ('timezone', models.FloatField(null=True, blank=True)),
                ('dst', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'zips2',
                'managed': False,
            },
        ),
    ]
